import type { DbDiscrepancy, RunDetail } from './db'

const PAGE_WIDTH = 612
const PAGE_HEIGHT = 792
const MARGIN = 42
const BLUE = [37, 99, 235] as const
const INK = [17, 24, 39] as const
const MUTED = [107, 114, 128] as const
const SOFT = [244, 246, 255] as const
const RED = [220, 38, 38] as const
const ORANGE = [249, 115, 22] as const
const GREEN = [16, 185, 129] as const

interface ProductSummary {
  productLine: string
  totalAtRisk: number
  discrepancyCount: number
}

export function buildRunPdf(run: RunDetail): Buffer {
  const pdf = new PdfBuilder()
  const generatedAt = new Date().toLocaleString('en-US')
  const runDate = new Date(run.created_at).toLocaleString('en-US')
  const productSummaries = parseProducts(run.product_line_summaries)
  const issueMix = buildIssueMix(run.discrepancies)
  const matchBase = Math.max(run.total_charges_records, run.total_invoices_records, 1)
  const matchRate = Math.round(((run.exact_matches + run.fuzzy_matches) / matchBase) * 100)

  pdf.addPage()
  pdf.header('Recona Reconciliation Report', `Generated ${generatedAt}`)
  pdf.text(`Run ${run.id}`, MARGIN, 700, 8, MUTED)
  pdf.text(`${run.charges_filename} x ${run.invoices_filename}`, MARGIN, 687, 9, MUTED)
  pdf.text(`Run date: ${runDate}`, MARGIN, 674, 9, MUTED)

  pdf.y = 640
  pdf.sectionTitle('Executive Summary')
  pdf.paragraph(run.ai_summary || 'No executive summary was generated for this run.', 10.5, 528)

  pdf.y -= 12
  pdf.cardGrid([
    { label: 'Issues', value: run.discrepancy_count.toLocaleString(), tone: RED },
    { label: 'At risk', value: money(run.total_amount_at_risk), tone: INK },
    { label: 'Revenue leakage', value: money(run.total_underbilled), tone: RED },
    { label: 'Overbilling', value: money(run.total_overbilled), tone: ORANGE },
    { label: 'Match rate', value: `${matchRate}%`, tone: GREEN },
    { label: 'AI matches', value: run.fuzzy_matches.toLocaleString(), tone: BLUE },
  ])

  pdf.sectionTitle('Risk Composition')
  pdf.keyValueRows([
    ['Underbilled revenue leakage', money(run.total_underbilled)],
    ['Overbilling / customer-impact exposure', money(run.total_overbilled)],
    ['Exact matches', run.exact_matches.toLocaleString()],
    ['AI-assisted fuzzy matches', run.fuzzy_matches.toLocaleString()],
    ['Rows reviewed', (run.total_charges_records + run.total_invoices_records).toLocaleString()],
    ['Fee schedule used', run.has_fee_schedule ? 'Yes' : 'No'],
  ])

  pdf.sectionTitle('Issue Mix')
  pdf.keyValueRows(issueMix.map((item) => [issueLabel(item.type), item.count.toLocaleString()]))

  pdf.sectionTitle('Product Exposure')
  if (productSummaries.length === 0) {
    pdf.text('No product exposure breakdown available.', MARGIN, pdf.y, 9, MUTED)
    pdf.y -= 18
  } else {
    pdf.table(
      ['Product line', 'Issues', 'At risk'],
      productSummaries.slice(0, 8).map((product) => [
        product.productLine || 'Unknown',
        product.discrepancyCount.toLocaleString(),
        money(product.totalAtRisk),
      ]),
      [285, 80, 120]
    )
  }

  pdf.sectionTitle('Top Discrepancies')
  const topDiscrepancies = run.discrepancies.slice(0, 14)
  if (topDiscrepancies.length === 0) {
    pdf.text('No discrepancies were found in this run.', MARGIN, pdf.y, 9, MUTED)
    pdf.y -= 18
  } else {
    pdf.table(
      ['Merchant', 'Type', 'Status', 'At risk'],
      topDiscrepancies.map((d) => [
        d.merchant_name,
        issueLabel(d.type),
        statusLabel(d),
        money(d.amount_at_risk),
      ]),
      [190, 150, 90, 90]
    )
  }

  pdf.sectionTitle('Recommended Workflow')
  pdf.numbered([
    'Assign unresolved issues to an owner from the Issues tab.',
    'Work assigned discrepancies from Queue and update notes/status.',
    'Approve suggested fixes from Resolutions.',
    'Track recovered revenue and reversals in Scorecard.',
  ])

  pdf.footer()
  return pdf.render()
}

class PdfBuilder {
  private pages: string[] = []
  private content = ''
  y = 720

  addPage() {
    if (this.content) this.pages.push(this.content)
    this.content = ''
    this.y = 720
    this.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, [248, 250, 255])
  }

  header(title: string, subtitle: string) {
    this.rect(0, 742, PAGE_WIDTH, 50, [239, 246, 255])
    this.rect(MARGIN, 758, 28, 28, BLUE)
    this.text('*', MARGIN + 10, 765, 18, [255, 255, 255], true)
    this.text('RECONA', MARGIN + 42, 773, 8, BLUE, true)
    this.text(title, MARGIN + 42, 756, 18, INK, true)
    this.text(subtitle, PAGE_WIDTH - 210, 764, 9, MUTED)
  }

  footer() {
    this.text('Confidential reconciliation report. Generated by Recona.', MARGIN, 26, 8, MUTED)
    this.text('recona-ai.vercel.app', PAGE_WIDTH - 140, 26, 8, BLUE)
  }

  sectionTitle(label: string) {
    this.ensureSpace(46)
    this.y -= 18
    this.text(label, MARGIN, this.y, 13, INK, true)
    this.y -= 14
    this.line(MARGIN, this.y, PAGE_WIDTH - MARGIN, this.y, [219, 234, 254])
    this.y -= 14
  }

  paragraph(text: string, size = 10, width = 500) {
    const lines = wrap(text, width, size)
    for (const line of lines.slice(0, 12)) {
      this.ensureSpace(14)
      this.text(line, MARGIN, this.y, size, INK)
      this.y -= 14
    }
  }

  cardGrid(cards: { label: string; value: string; tone: readonly number[] }[]) {
    const cardWidth = 165
    const cardHeight = 58
    let x = MARGIN
    for (let index = 0; index < cards.length; index += 1) {
      if (index === 3) {
        x = MARGIN
        this.y -= cardHeight + 12
      }
      this.ensureSpace(cardHeight + 18)
      const card = cards[index]
      this.rect(x, this.y - cardHeight + 8, cardWidth, cardHeight, [255, 255, 255])
      this.text(card.label.toUpperCase(), x + 12, this.y - 12, 7.5, MUTED, true)
      this.text(card.value, x + 12, this.y - 36, 16, card.tone, true)
      x += cardWidth + 14
    }
    this.y -= cardHeight + 18
  }

  keyValueRows(rows: string[][]) {
    for (const [label, value] of rows) {
      this.ensureSpace(18)
      this.text(label, MARGIN, this.y, 9, MUTED)
      this.text(value, PAGE_WIDTH - MARGIN - 170, this.y, 9.5, INK, true)
      this.y -= 17
    }
  }

  table(headers: string[], rows: string[][], widths: number[]) {
    this.ensureSpace(38)
    let x = MARGIN
    this.rect(MARGIN, this.y - 20, PAGE_WIDTH - MARGIN * 2, 24, [239, 246, 255])
    headers.forEach((header, index) => {
      this.text(header.toUpperCase(), x + 8, this.y - 11, 7.5, BLUE, true)
      x += widths[index]
    })
    this.y -= 28

    for (const row of rows) {
      this.ensureSpace(25)
      x = MARGIN
      this.line(MARGIN, this.y + 7, PAGE_WIDTH - MARGIN, this.y + 7, [229, 231, 235])
      row.forEach((cell, index) => {
        this.text(truncate(cell, index === 0 ? 28 : 22), x + 8, this.y - 4, 8.5, index === row.length - 1 ? RED : INK)
        x += widths[index]
      })
      this.y -= 24
    }
  }

  numbered(items: string[]) {
    for (let index = 0; index < items.length; index += 1) {
      this.ensureSpace(22)
      this.rect(MARGIN, this.y - 12, 16, 16, BLUE)
      this.text(String(index + 1), MARGIN + 5, this.y - 8, 8, [255, 255, 255], true)
      this.text(items[index], MARGIN + 26, this.y - 7, 9, INK)
      this.y -= 22
    }
  }

  ensureSpace(height: number) {
    if (this.y - height < 54) {
      this.footer()
      this.addPage()
    }
  }

  rect(x: number, y: number, width: number, height: number, color: readonly number[]) {
    this.content += `${rgb(color)} ${fmt(x)} ${fmt(y)} ${fmt(width)} ${fmt(height)} re f\n`
  }

  line(x1: number, y1: number, x2: number, y2: number, color: readonly number[]) {
    this.content += `${strokeRgb(color)} 0.7 w ${fmt(x1)} ${fmt(y1)} m ${fmt(x2)} ${fmt(y2)} l S\n`
  }

  text(value: string, x: number, y: number, size: number, color: readonly number[], bold = false) {
    this.content += `BT ${rgb(color)} /${bold ? 'F2' : 'F1'} ${fmt(size)} Tf ${fmt(x)} ${fmt(y)} Td (${escapePdf(value)}) Tj ET\n`
  }

  render(): Buffer {
    if (this.content) this.pages.push(this.content)
    const objects: string[] = []
    objects.push('<< /Type /Catalog /Pages 2 0 R >>')
    const pageRefs = this.pages.map((_, index) => `${5 + index * 2} 0 R`).join(' ')
    objects.push(`<< /Type /Pages /Kids [${pageRefs}] /Count ${this.pages.length} >>`)
    objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')
    objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>')

    this.pages.forEach((page, index) => {
      const pageObjectId = 5 + index * 2
      const contentObjectId = pageObjectId + 1
      objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentObjectId} 0 R >>`)
      objects.push(`<< /Length ${Buffer.byteLength(page)} >>\nstream\n${page}endstream`)
    })

    let body = '%PDF-1.4\n'
    const offsets = [0]
    objects.forEach((object, index) => {
      offsets.push(Buffer.byteLength(body))
      body += `${index + 1} 0 obj\n${object}\nendobj\n`
    })
    const xrefOffset = Buffer.byteLength(body)
    body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
    offsets.slice(1).forEach((offset) => {
      body += `${String(offset).padStart(10, '0')} 00000 n \n`
    })
    body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`
    return Buffer.from(body)
  }
}

function parseProducts(value: unknown): ProductSummary[] {
  if (!Array.isArray(value)) return []
  return value
    .map((item) => item as Partial<ProductSummary>)
    .filter((item) => typeof item.productLine === 'string')
    .map((item) => ({
      productLine: item.productLine ?? 'Unknown',
      totalAtRisk: Number(item.totalAtRisk ?? 0),
      discrepancyCount: Number(item.discrepancyCount ?? 0),
    }))
    .sort((a, b) => b.totalAtRisk - a.totalAtRisk)
}

function buildIssueMix(discrepancies: DbDiscrepancy[]) {
  const counts = new Map<string, number>()
  for (const discrepancy of discrepancies) {
    counts.set(discrepancy.type, (counts.get(discrepancy.type) ?? 0) + 1)
  }
  return [...counts.entries()]
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 8)
}

function issueLabel(type: string) {
  return type.replaceAll('_', ' ').replace(/\b\w/g, (char) => char.toUpperCase())
}

function statusLabel(discrepancy: DbDiscrepancy) {
  if (discrepancy.status === 'in_review') return 'In review'
  return issueLabel(discrepancy.status ?? 'open')
}

function money(value: number) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value ?? 0))
}

function rgb(color: readonly number[]) {
  return `${color.map((part) => fmt(part / 255)).join(' ')} rg`
}

function strokeRgb(color: readonly number[]) {
  return `${color.map((part) => fmt(part / 255)).join(' ')} RG`
}

function fmt(value: number) {
  return Number(value.toFixed(3)).toString()
}

function escapePdf(value: string) {
  return normalize(value).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

function normalize(value: string) {
  return String(value)
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/[–—]/g, '-')
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, '')
}

function truncate(value: string, maxLength: number) {
  const normalized = normalize(value)
  return normalized.length > maxLength ? `${normalized.slice(0, maxLength - 1)}...` : normalized
}

function wrap(text: string, width: number, size: number) {
  const maxChars = Math.max(20, Math.floor(width / (size * 0.48)))
  const words = normalize(text).split(/\s+/).filter(Boolean)
  const lines: string[] = []
  let current = ''
  for (const word of words) {
    const next = current ? `${current} ${word}` : word
    if (next.length > maxChars && current) {
      lines.push(current)
      current = word
    } else {
      current = next
    }
  }
  if (current) lines.push(current)
  return lines
}
